on: 
 schedule:
    # This cron syntax runs at midnight UTC every day
    - cron: '50 15 * * *'
 workflow_dispatch:
      inputs:
        plans:
          description: 'Mabl Deployment to run'
          default: 'GIT_Test'

name: mabl
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: mabl Test
  
    steps:
      - uses: actions/checkout@v4

      - name: Functional test deployment
        id: mabl-test-deployment
        uses: mablhq/github-run-tests-action@v1
        env:
          # Use a "CI/CD Integration" type of mabl API key
          MABL_API_KEY: CBPEvDYpcJJecsLvwNjFSg
         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          application-id: bA7pKxy2ROhoNKoOUgmxLw-a
          environment-id: afhRPUOL8YBA8Rv07y108w-e
          plan-labels: GIT_Test
